//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BISConManager.rc
//
#define IDR_MENU_LISTBOX                4
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_PROPPAGE_1                  104
#define IDR_MAINFRAME                   128
#define IDR_BISCONTYPE                  129
#define IDR_IVRCONTYPE                  129
#define IDD_STATEDLG                    130
#define IDB_BITMAP1                     130
#define IDR_MENU_POP_LIST               130
#define IDI_ICON1                       131
#define IDI_ICON2                       132
#define IDB_BITMAP2                     132
#define IDI_ICON3                       133
#define IDD_DLG_CINF                    134
#define IDI_ICON1R                      135
#define IDD_PROPPAGE_7                  135
#define IDI_ICON2R                      136
#define IDD_PROPPAGE_Q931               136
#define IDI_ICON3R                      137
#define IDD_PROPPAGE_CODEC              137
#define IDD_DLG_PROC                    142
#define BINETLOGO                       143
#define IDB_BIT_ADDRESS                 145
#define IDB_BINETLP                     146
#define IDI_START                       148
#define IDI_STOP                        149
#define IDB_TELSTATE                    149
#define IDB_TELSTATELARGE               150
#define IDB_DONGSEOLOGO                 151
#define IDB_DONGSERSMALLLOGO            153
#define IDB_START_REG                   154
#define IDB_STOP_REG                    155
#define IDB_START_UNREG                 156
#define IDB_STOP_UNREG                  157
#define IDD_PROPPAGE_2                  160
#define IDD_PROPPAGE_3                  161
#define IDD_PROPPAGE_4                  162
#define IDD_PROPPAGE_5                  163
#define IDD_PROPPAGE_6                  164
#define IDC_ED_TOTAL                    1001
#define IDC_LIST2                       1002
#define IDC_ED_CUR_CALL                 1004
#define IDC_ED_NEW_LANGUAGE             1005
#define IDC_ED_NUM                      1005
#define IDC_TN_NEW_LAN                  1006
#define IDC_ED_STEP                     1006
#define IDC_CHK_FASTSTAR                1006
#define IDC_ED_SRC                      1007
#define IDC_CHK_H245TUNNELING           1007
#define IDC_ED_DES                      1008
#define IDC_RTPPort                     1008
#define IDC_ED_STATE                    1009
#define IDC_Q931CallSinalPort           1009
#define IDC_RASResponseTimeout          1009
#define IDC_ED_PIN                      1010
#define IDC_RASPort                     1010
#define IDC_MulticastPort               1011
#define IDC_MulticastIP                 1012
#define IDC_E164ID2                     1013
#define IDC_STATICMAXCALL               1014
#define IDC_CHK_SECONDE164              1015
#define IDC_GATEKEEPERIP                1018
#define IDC_BTN_UPDATE                  1018
#define IDC_GateKeeperPort              1019
#define IDC_ED_NEWE164                  1019
#define IDC_E164ID                      1020
#define IDC_H323ID                      1021
#define IDC_LB_E164                     1022
#define IDC_Q931CallSinallingPort       1023
#define IDC_ConnectTimeout              1024
#define IDC_ResponseTimeout             1025
#define IDC_TTL                         1027
#define IDC_CHK_OVERLAPSENDING          1027
#define IDC_MENTTIMEOUT                 1028
#define IDC_TTLVALUE                    1028
#define IDC_DTMFTIMEOUT                 1029
#define IDC_MAXFAIL                     1029
#define IDC_DTMFINITTIMEOUT             1030
#define IDC_LANGUAGE                    1031
#define IDC_TOTALCALLTITLE              1034
#define IDC_CHKSILENCESUPRESSION        1034
#define IDC_CHK_AUTO_TERMINAL           1035
#define IDC_EDAUDIOFRAME                1035
#define IDC_PROGRESS                    1036
#define IDC_CURRENTCALLTITLE            1036
#define IDC_CBAUDIO1                    1036
#define IDC_CHECK1                      1037
#define IDC_CBAUDIO3                    1037
#define IDC_CHECK2                      1038
#define IDC_CBAUDIO2                    1038
#define IDC_CHECK3                      1039
#define IDC_CHKDTMFENABLE               1039
#define IDC_CBDTMFTYPE                  1040
#define IDC_BTN_MAIL                    1041
#define IDC_CHK1                        1041
#define IDC_BTN_HTTP                    1042
#define IDC_CHK2                        1042
#define IDC_CHK3                        1043
#define IDC_CHKAUDIORECORD              1043
#define IDC_CHKRTPREARRANGE             1044
#define IDC_LIST_SCE                    1045
#define IDC_CHKAUDIORECORD2             1046
#define IDC_SCEFIND                     1054
#define IDC_SYSTEMMAXCALL               1056
#define ID_IVR_START                    4464
#define ID_IVR_STOP                     4465
#define IDM_POP_RESET                   32771
#define IDM_POP_CALLINFO                32772
#define ID_APP_IVR_START                32776
#define ID_APP_IVR_STOP                 32777
#define ID_APP_HELP                     32782
#define IDM_CONFIG                      32783
#define IDM_SETCONF                     32791
#define IDS_STATESTR                    57638
#define IDS_CONFIGSTR                   57639
#define IDS_ERROR_PORT                  57646
#define IDS_ERROR_IP                    57647
#define IDS_IVR_START                   57654
#define IDS_IVR_STOP                    57655
#define IDS_TERMINAL_START              57656
#define IDS_TERMINAL_STOP               57657
#define ID_STATUS_STR                   61448
#define IDM_VOICON_START                61449
#define IDM_VOICON_STOP                 61450
#define IDM_TM_START                    61451
#define IDM_TM_STOP                     61452

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
