#ifndef __USERMSGH__
#define __USERMSGH__

typedef enum
{
	UM_KEYIN = (WM_USER+10),
	UM_MAKECALL,
	UM_NEWINCALL,
	UM_ACCEPTCALL,
	UM_ANSWERCALL,
	UM_DROPCALL,
	UM_RASMSG,
	UM_Q931MSG,
	UM_REQOUTRTP,
	UM_REQINRTP,
	UM_CLOSEINRTP,
	UM_CLOSEOUTRTP,
	UM_SETOUTRTCP_RMTADDR,
	UM_SETOUTRTP_RMTADDR,
	UM_SETINRTCP_RMTADDR,
	UM_SETINRTP_RMTADDR,
	UM_SENDMEDIA,
	UM_SENDDTMF,
	UM_MEDIAQUIT,
	UM_CHANGEGK,
	UM_CALL_BUSY,
	UM_CALL_REMOTEWAITING,
	UM_CALL_CONNECTED,
	UM_CLOSEINDEV,
	UM_CLOSEOUTDEV,
	UM_OPENINDEV,
	UM_OPENOUTDEV,
	UM_PLAYDTMF
} UMMSG;

#endif
