//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ScenarioEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_SCENARTYPE                  129
#define IDD_VIEW_PAGE1                  130
#define IDD_VIEW_PAGE2                  131
#define IDI_ARROW                       132
#define IDI_EQUAL                       133
#define IDI_ANDOR                       134
#define IDI_CIRCUIT                     135
#define IDI_MATH                        136
#define IDI_IS                          137
#define IDI_RETRIAL                     138
#define IDI_SPEAK                       139
#define IDI_INIT                        140
#define IDI_DTMF                        141
#define IDI_PHONE                       142
#define IDI_PLUG                        143
#define IDI_WATCH                       144
#define IDR_MENU_POPUP                  146
#define IDI_GOTO                        147
#define IDD_GOTO_PAGE1                  148
#define IDB_BMP_LOGO                    149
#define IDI_HUB                         151
#define IDD_TEL_PAGE_1                  152
#define IDD_TEL_PAGE_2                  153
#define IDD_INIT_PAGE_1                 154
#define IDD_INIT_PAGE_2                 155
#define IDD_PLAY_PAGE_1                 156
#define IDD_PLAY_PAGE_2                 157
#define IDD_HUB_PAGE1                   158
#define IDI_PAGE                        159
#define IDD_PAGE_PAGE1                  160
#define IDD_TIMECHK_PAGE_1              161
#define IDD_TIMECHK_PAGE_2              162
#define IDD_PAGE_PAGE2                  163
#define IDD_INPUT_PAGE_1                164
#define IDD_INPUT_PAGE_2                165
#define IDD_INPUT_PAGE_3                166
#define IDI_VOICE_REC                   167
#define IDD_PLUG_PAGE_1                 168
#define IDD_PLUG_PAGE_2                 169
#define IDR_MENU_LISTBOX                170
#define IDD_VOICEREC_PAGE1              170
#define IDD_VOICEREC_PAGE2              171
#define IDD_LOOP_PAGE_1                 172
#define IDI_CALLERR                     172
#define IDD_CALLERR_PAGE_1              173
#define IDD_MATH_PAGE_1                 174
#define IDD_MATH_PAGE_2                 176
#define IDD_LOGICALCON_PAGE_1           178
#define IDD_LOGICALCON_PAGE_2           179
#define IDD_CONDITION_PAGE_1            180
#define IDD_CONDITION_PAGE_2            181
#define IDD_IS_PAGE_1                   186
#define IDD_RETRIAL_PAGE_1              188
#define IDD_HUB_PAGE2                   189
#define IDD_CALLERR_PAGE_2              203
#define IDC_CB_INBUF                    204
#define IDC_REFRESH_UINPUT              205
#define IDC_BTN_INIT                    1000
#define IDC_BTN_MATH                    1001
#define IDC_BTN_IS                      1002
#define IDC_BTN_EQUAL                   1003
#define IDC_BTN_ANDOR                   1004
#define IDC_BTN_CIRCUIT                 1005
#define IDC_ED_ID                       1005
#define IDC_BTN_PHONE                   1006
#define IDC_LIST_MENT                   1006
#define IDC_BTN_PLUG                    1007
#define IDC_BTN_SPEAK                   1008
#define IDC_BTN_RETRIAL                 1009
#define IDC_BTN_WATCH                   1010
#define IDC_BTN_VOICE_REC               1011
#define IDC_BTN_DTMF                    1012
#define IDC_ST_CURID                    1013
#define IDC_ST_TYPE                     1014
#define IDC_CHK_OUTISFREE               1014
#define IDC_ST_GO                       1015
#define IDC_ED_GOTO                     1015
#define IDC_ST_FALSEGO                  1016
#define IDC_ED_RETRIAL_COUNT            1016
#define IDC_BTN_GOTO                    1017
#define IDC_ED_RETRIAL_POINT            1017
#define IDC_BTN_HUB                     1018
#define IDC_CB_DIREC                    1019
#define IDC_BTN_PAGE                    1019
#define IDC_LIST_GOTO                   1024
#define IDC_ED_SCENAME                  1025
#define IDC_ED_MENT                     1027
#define IDC_BTN_MENT                    1028
#define IDC_LIST_SCENARIO               1028
#define IDC_CHK_CALLDROP                1029
#define IDC_CHK_AUTOCALL                1030
#define IDC_LIST_TELNUM                 1031
#define IDC_ED_TELNUM                   1032
#define IDC_BTN_NEW                     1033
#define IDC_CHKDAILY                    1034
#define IDC_CHK_BUSYRETRY               1034
#define IDC_CHK_01                      1034
#define IDC_EDGO                        1035
#define IDC_CHK_02                      1035
#define IDC_EDSTARTHOUR                 1036
#define IDC_CHK_USER                    1036
#define IDC_CHK_RECV                    1037
#define IDC_EDSTARTMINUTE               1038
#define IDC_CHK_BOTH                    1038
#define IDC_EDENDHOUR                   1039
#define IDC_RD_EXIT1                    1039
#define IDC_EDENDMINUTE                 1040
#define IDC_CHKSPECIALDAY               1040
#define IDC_RD_RETURN1                  1040
#define IDC_RD1                         1041
#define IDC_RD_CHARA1                   1041
#define IDC_RD2                         1042
#define IDC_RD_BACK1                    1042
#define IDC_RD3                         1043
#define IDC_RD_EXIT2                    1043
#define IDC_RD4                         1044
#define IDC_RD_RETURN2                  1044
#define IDC_CHK_CALLEE                  1044
#define IDC_RD5                         1045
#define IDC_RD_CHARA2                   1045
#define IDC_CHK_CALLER                  1045
#define IDC_EDBUFLENGTH                 1046
#define IDC_RD_BACK2                    1046
#define IDC_ED_DFNAME                   1046
#define IDC_BTN_OPEN_DFNAME             1047
#define IDC_EDDLLANEM                   1048
#define IDC_ED_SFNAME                   1048
#define IDC_EDFUNCTION                  1049
#define IDC_BTN_SP_OPEN                 1049
#define IDC_LISTINBUFFER                1050
#define IDC_CHK_V_REC                   1050
#define IDC_CHK_V_PLAY                  1051
#define IDC_CB_STOPKEY                  1054
#define IDC_ED_DATA_EXPIRE              1055
#define IDC_CB_DELKEY                   1056
#define IDC_ED_NUM                      1057
#define IDC_CHK_V_MANAGE                1057
#define IDC_RD11                        1058
#define IDC_RD12                        1059
#define IDC_RD13                        1060
#define IDC_BTN_CALLERR                 1060
#define IDC_RD14                        1061
#define IDC_RD15                        1062
#define IDC_ED_SPE_GOTO                 1065
#define IDC_CHK_VDELETE                 1065
#define IDC_ED_ANNOUNCE                 1066
#define IDC_ED_DEFCALLDURATION          1072
#define IDC_COMBO_LEFT                  1073
#define IDC_COMBO_RIGHT                 1074
#define IDC_COMBO_ARG                   1075
#define IDC_RD_BUSY                     1081
#define IDC_COMBO_ANSWER                1082
#define IDC_RD_NOANS                    1082
#define IDC_COMBO_OUTPUT                1083
#define IDC_RD_NOTFOUND                 1083
#define IDC_COMBO_INPUT                 1084
#define IDC_ED_VALUE                    1087
#define IDC_COMBO_COMMAND               1089
#define IDM_ITEM_LINK                   32772
#define IDM_SETCONF                     32772
#define IDM_ITEM_UNLINK                 32773
#define IDM_ITEM_PROPERTIES             32774
#define ID_LISTBOXCONTROL_MAPPINGDTMFKEYVALUE 32775
#define IDM_MAPPING_DTMF                32776
#define ID__SETDTMF                     32777
#define ID_SETDTMF_1                    32778
#define ID_SETDTMF_2                    32779
#define ID_SETDTMF_3                    32780
#define ID_SETDTMF_4                    32781
#define ID_SETDTMF_5                    32782
#define ID_SETDTMF_6                    32783
#define ID_SETDTMF_7                    32784
#define ID_SETDTMF_8                    32785
#define ID_SETDTMF_9                    32786
#define ID_SETDTMF_0                    32787
#define ID_SETDTMF_                     32788
#define ID_SETDTMF_32789                32789
#define IDM_DTMF_1                      32790
#define IDM_DTMF_2                      32791
#define IDM_DTMF_3                      32792
#define IDM_DTMF_4                      32793
#define IDM_DTMF_5                      32794
#define IDM_DTMF_6                      32795
#define IDM_DTMF_7                      32796
#define IDM_DTMF_8                      32797
#define IDM_DTMF_9                      32798
#define IDM_DTMF_0                      32799
#define IDM_DTMF_STAR                   32800
#define IDM_DTMF_SHARP                  32801
#define IDS_INARG1                      61447
#define IDS_INARG2                      61448
#define IDS_INARG3                      61449
#define IDS_INARG5                      61450
#define IDS_INARG6                      61451
#define IDS_INARG7                      61452
#define IDS_INARG8                      61453
#define IDS_INARG9                      61454
#define IDS_OUTARG0                     61455
#define IDS_OUTARG1                     61456
#define IDS_OUTARG3                     61458
#define IDS_OUTARG4                     61459
#define IDS_INARG4                      61460
#define IDS_INARG11                     61461
#define IDS_INARG22                     61462
#define IDS_INARG23                     61463
#define IDS_INARG20                     61464
#define IDS_INARG21                     61465
#define IDS_INARG24                     61466
#define IDS_INARG10                     61467
#define IDS_OUTARG11                    61468
#define IDS_OUTARG12                    61469
#define IDS_INARG0                      61470
#define IDS_OUTARG2                     61471

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
